=begin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class RestaurantsController < ApplicationController

  def get_restaurant_configuration
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
