=begin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class WaitlistController < ApplicationController
  before_action :set_restaurant, only: [ :join ]
  before_action :set_party, only: [ :check_in, :destroy ]
  before_action :set_restaurant_from_party, only: [ :show, :destroy ]

  def check_in
    # Verify the party position on the waitlist
    if @restaurant.waitlist.first._id != @party._id or @restaurant.current_capacity < @party.size
      render json: { message: "Check-in isn't available for this party yet." }, status: :forbidden
      return
    end

    @restaurant.current_capacity -= @party.size
    @restaurant.save
    @party.destroy

    # TODO Start party service.

    render status: :ok
  end

  # Retrieve the party position in the waitlist.
  def show
    # TODO 
    render status: :not_implemented
  end

  # Add the party to the restaurant waitlist.
  def join
    party_params = params.expect(waitlist: [:name, :party_size])

    if party_params[:party_size] > @restaurant.max_party_size
      render json: { "message" => "Party size cannot exceed #{@restaurant.max_party_size}" }
    end

    party = Party.new(party_params)

    @restaurant.waitlist.push(party)

    if @restaurant.save
      render json: party, status: :created
    end

    # render json: @party
  end

  # Delete the party from the waitlist.
  def destroy
    @party.destroy
    render status: :no_content
  end

  private

  # Retrieve the original restaurant
  def set_restaurant
    @restaurant = Restaurant.find(params.expect(:restaurant_uuid))
  end

  # Retrieve the original party
  def set_restaurant_from_party
    @restaurant = Restaurant.find_by("waitlist._id" => params.expect(:uuid))
  end

  def set_party
    @restaurant = set_restaurant_from_party
    @party = @restaurant.waitlist.find(params[:uuid])
  end
end
